#!/usr/bin/env python3

import argparse

import anyio

import aiorosbridge.server


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--port", type=int, default=9090)
    parser.add_argument("-d", "--debug", action="store_true")
    args = parser.parse_args()
    anyio.run(aiorosbridge.server.run, args.port, None, args.debug)


if __name__ == "__main__":
    main()
